name: robboli_broc
version: 1.0.0
config-version: 2
profile: default

clean-targets:
  - target
  - dbt_modules

models:
  robboli_broc:
    base:
      materialized: ephemeral
    staging:
      materialized: table
    marts:
      fantasy_football:
        materialized: table

seeds:
  robboli_broc:
    lookup__matchup_corrections:
      +column_types:
        matchup_id: STRING
