name: robboli_broc
version: 1.0.0
config-version: 2

clean-targets:
  - "target"
  - "dbt_modules"

models:
  robboli_broc:
    base:
      materialized: ephemeral
    staging:
      materialized: table
    marts:
      fantasy_football:
        materialized: table

seeds:
  robboli_broc:
    lookup_matchup_corrections:
      +column_types:
        season_id: STRING
